apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: app-config
    files:
      - alpha.properties=configs/alpha.properties
      - bravo.properties=configs/bravo.properties
