apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

#transformers:
#  - merge.yaml

configMapGenerator:
  - name: app-config
    behavior: merge
    envs:
      - props.env
    files:
      - configs/alpha-a.properties
      - configs/alpha-b.properties
      - configs/bravo-a.properties